import { Router } from "express";
import healthRouter from "./health";
import categoriesRouter from "./categories";
import articlesRouter from "./articles";
import authRouter from "./auth";
import usersRouter from "./users";
import rolesRouter from "./roles";
import contactRouter from "./contact";
import newsletterRouter from "./newsletter";
import searchRouter from "./search";
import mediaRouter from "./media";
import commentsRouter from "./comments";
import tagsRouter from "./tags";
import campaignsRouter from "./campaigns";
import templatesRouter from "./templates";
import automationsRouter from "./automations";
import trackingRouter from "./tracking";
import analyticsRouter from "./analytics";
import reportsRouter from "./reports";
import settingsRouter from "./settings";
import advertisersRouter from "./advertisers";
import adCampaignsRouter from "./adCampaigns";
import advertisementsRouter from "./advertisements";
import dashboardRouter from "./dashboard";
import workflowRouter from "./workflow";
import seoRouter from "./seo";
import layoutsRouter from "./layouts";

const router = Router();

router.use("/health", healthRouter);
router.use("/categories", categoriesRouter);
router.use("/articles", articlesRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/roles", rolesRouter);
router.use("/contact", contactRouter);
router.use("/newsletter", newsletterRouter);
router.use("/search", searchRouter);
router.use("/media", mediaRouter);
router.use("/comments", commentsRouter);
router.use("/tags", tagsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/newsletter/campaigns", campaignsRouter);
router.use("/newsletter/templates", templatesRouter);
router.use("/newsletter/automations", automationsRouter);
router.use("/tracking", trackingRouter);
router.use("/newsletter/reports", reportsRouter);
router.use("/newsletter/settings", settingsRouter);

router.use("/advertisers", advertisersRouter);
router.use("/ad-campaigns", adCampaignsRouter);
router.use("/advertisements", advertisementsRouter);
router.use("/editorial", workflowRouter);
router.use("/analytics", analyticsRouter);
router.use("/layouts", layoutsRouter);
router.use("/", seoRouter);

export default router;
